using System.Collections.Generic;
using System.IO;
using System.Text;
using GuardWui3.Models;

namespace GuardWui3.Services;

// Generates guard-backup.cmd, a fully standalone Robocopy script that runs the
// same from the app, Task Scheduler, or a double-click.
public static class BackupScript
{
    public static void Write(Settings cfg)
    {
        string mirror = cfg.Mode == "Mirror" ? "/MIR" : "/E";
        string exDirs = ToOneLine(cfg.ExcludeDirs);
        string exFiles = ToOneLine(cfg.ExcludeFiles);
        var opts = new StringBuilder();
        // /XJ is MANDATORY: skips junction points. Without it the hidden
        // My Music / My Pictures / My Videos junctions in Documents cause
        // failed-directory errors on every run.
        opts.Append(mirror).Append(" /R:2 /W:5 /MT:16 /NP /NFL /NDL /XJ");
        if (exDirs.Length > 0) opts.Append(" /XD ").Append(exDirs);
        if (exFiles.Length > 0) opts.Append(" /XF ").Append(exFiles);

        var sb = new StringBuilder();
        sb.AppendLine("@echo off");
        sb.AppendLine("setlocal EnableExtensions");
        sb.AppendLine("REM ===========================================================================");
        sb.AppendLine("REM  guard-backup.cmd  -  GENERATED by GUARD.exe. Do not hand-edit;");
        sb.AppendLine("REM  your changes will be overwritten the next time you Save in the app.");
        sb.AppendLine("REM");
        sb.AppendLine("REM  USAGE:");
        sb.AppendLine("REM    guard-backup.cmd          run the backup for real (keeps window open)");
        sb.AppendLine("REM    guard-backup.cmd test     PREVIEW only - shows what WOULD change");
        sb.AppendLine("REM    guard-backup.cmd auto     silent (used by the scheduled task)");
        sb.AppendLine("REM    guard-backup.cmd onconnect");
        sb.AppendLine("REM                              silent; backs up only if the destination is");
        sb.AppendLine("REM                              reachable and no backup succeeded yet today");
        sb.AppendLine("REM                              (used by the on-connect scheduled task)");
        sb.AppendLine("REM ===========================================================================");
        sb.AppendLine();
        sb.AppendLine("set \"DEST=" + cfg.Dest + "\"");
        sb.AppendLine("set \"LOGDIR=%~dp0Logs\"");
        sb.AppendLine("set \"LOG=%LOGDIR%\\backup_last.log\"");
        sb.AppendLine();
        sb.AppendLine("set \"DRY=\"");
        sb.AppendLine("set \"PAUSEATEND=1\"");
        sb.AppendLine("if /I \"%~1\"==\"test\" set \"DRY=/L\"");
        sb.AppendLine("if /I \"%~1\"==\"auto\" set \"PAUSEATEND=\"");
        sb.AppendLine("if /I \"%~1\"==\"onconnect\" set \"PAUSEATEND=\"");
        sb.AppendLine("if /I \"%~1\"==\"onconnect\" set \"ONCONNECT=1\"");
        sb.AppendLine();
        // On-connect gate: the periodic task fires this every few minutes, so it
        // must cost nothing when there is nothing to do. Exit silently (and before
        // the log header, so the last real backup log is never overwritten) when
        // the destination is absent or the stamp already records a successful run
        // today. The stamp holds %DATE% verbatim; findstr /x compares it the same
        // way it was written, so locale date formats are irrelevant. A failed run
        // does not update the stamp (see the HADERR branch), so the next check
        // retries instead of skipping the rest of the day.
        sb.AppendLine("set \"OCSTAMP=%~dp0onconnect-stamp.txt\"");
        sb.AppendLine("if not defined ONCONNECT goto :checked");
        sb.AppendLine("if not exist \"%DEST%\\\" exit /b 0");
        sb.AppendLine("findstr /l /x /c:\"%DATE%\" \"%OCSTAMP%\" >nul 2>&1");
        sb.AppendLine("if not errorlevel 1 exit /b 0");
        sb.AppendLine(":checked");
        sb.AppendLine();
        sb.AppendLine("set \"OPTS=" + opts + "\"");
        sb.AppendLine();
        sb.AppendLine("if not exist \"%LOGDIR%\" md \"%LOGDIR%\"");
        sb.AppendLine();
        sb.AppendLine(">\"%LOG%\"  echo ===========================================================");
        sb.AppendLine(">>\"%LOG%\" echo  Backup     %date% %time%");
        sb.AppendLine(">>\"%LOG%\" echo  Destination: %DEST%");
        sb.AppendLine("if defined DRY >>\"%LOG%\" echo  *** PREVIEW MODE - no changes made ***");
        sb.AppendLine(">>\"%LOG%\" echo ===========================================================");
        sb.AppendLine();
        sb.AppendLine("echo.");
        sb.AppendLine("echo Backup    destination: %DEST%");
        sb.AppendLine("if defined DRY echo *** PREVIEW MODE - nothing will be copied or deleted ***");
        sb.AppendLine("echo Log file: %LOG%");
        sb.AppendLine("echo.");
        sb.AppendLine();
        sb.AppendLine("if not exist \"%DEST%\\\" (");
        sb.AppendLine("   echo ERROR: destination not reachable at %DEST%  - aborting.");
        sb.AppendLine("   >>\"%LOG%\" echo ERROR: destination not reachable at %DEST% - aborting.");
        sb.AppendLine("   goto :end");
        sb.AppendLine(")");
        sb.AppendLine();
        sb.AppendLine("set \"HADERR=\"");
        sb.AppendLine();
        // @@PROGRESS@@ markers feed the app's progress bar; emitted only under
        // GUARD_UI, sent to stdout only (never the log).
        var inc = new List<FolderPair>();
        foreach (var f in cfg.Folders) if (f.Include) inc.Add(f);
        for (int i = 0; i < inc.Count; i++)
        {
            var f = inc[i];
            sb.AppendLine("if defined GUARD_UI echo @@PROGRESS@@ " + (i + 1) + " " + inc.Count + " " + MarkerSafe(f.SubFolder));
            sb.AppendLine("call :backup \"" + f.Source + "\" \"%DEST%\\" + f.SubFolder + "\"");
        }
        sb.AppendLine("if defined GUARD_UI echo @@PROGRESS@@ DONE");
        sb.AppendLine();
        sb.AppendLine(">>\"%LOG%\" echo.");
        sb.AppendLine("if defined HADERR (");
        sb.AppendLine("   >>\"%LOG%\" echo FINISHED WITH ERRORS   %date% %time%");
        sb.AppendLine("   echo.");
        sb.AppendLine("   echo Backup finished, but some folders reported errors - see the log.");
        sb.AppendLine(") else (");
        sb.AppendLine("   >>\"%LOG%\" echo FINISHED OK   %date% %time%");
        sb.AppendLine("   echo.");
        sb.AppendLine("   echo Backup finished successfully.");
        // Stamp only clean on-connect runs (an error should retry on the next
        // check, and the DRY guard is belt-and-braces; the task never passes
        // "test"). %DATE% expands when this block executes, i.e. at the finish,
        // so a run crossing midnight stamps the new day as already covered.
        sb.AppendLine("   if defined ONCONNECT if not defined DRY >\"%OCSTAMP%\" echo %DATE%");
        sb.AppendLine(")");
        sb.AppendLine("goto :end");
        sb.AppendLine();
        sb.AppendLine(":backup");
        sb.AppendLine("if not exist \"%~1\" (");
        sb.AppendLine("   echo SKIP  source not found: %~1");
        sb.AppendLine("   >>\"%LOG%\" echo.");
        sb.AppendLine("   >>\"%LOG%\" echo SKIP source not found: %~1");
        sb.AppendLine("   goto :eof");
        sb.AppendLine(")");
        sb.AppendLine("echo Backing up: %~1");
        sb.AppendLine(">>\"%LOG%\" echo.");
        sb.AppendLine(">>\"%LOG%\" echo --- %~1  =^> %~2");
        sb.AppendLine("robocopy \"%~1\" \"%~2\" %OPTS% %DRY% /LOG+:\"%LOG%\" /TEE");
        sb.AppendLine("if errorlevel 8 (");
        sb.AppendLine("   set \"HADERR=1\"");
        sb.AppendLine("   echo    !! errors copying %~1 - see the log");
        sb.AppendLine(")");
        sb.AppendLine("goto :eof");
        sb.AppendLine();
        sb.AppendLine(":end");
        sb.AppendLine("endlocal");
        sb.AppendLine("echo.");
        sb.AppendLine("if defined PAUSEATEND pause");
        File.WriteAllText(GuardPaths.ScriptPath, sb.ToString());
    }

    // Strip characters that would break a batch `echo` so a subfolder name is
    // safe to embed in an @@PROGRESS@@ marker line.
    private static string MarkerSafe(string s)
    {
        if (string.IsNullOrEmpty(s)) return "";
        var sb = new StringBuilder();
        foreach (char c in s)
            sb.Append("&<>|^%\"".IndexOf(c) >= 0 ? ' ' : c);
        return sb.ToString().Trim();
    }

    private static string ToOneLine(string multiline)
    {
        if (string.IsNullOrEmpty(multiline)) return "";
        // Handle every newline form, including the bare CR a WinUI multi-line
        // TextBox uses, so each excluded name becomes its own /XD or /XF token.
        var parts = multiline.Replace("\r\n", "\n").Replace("\r", "\n").Split('\n');
        var keep = new List<string>();
        foreach (var p in parts) { var t = p.Trim(); if (t.Length > 0) keep.Add(t); }
        return string.Join(" ", keep.ToArray());
    }
}
