using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using GuardWui3.Models;

namespace GuardWui3.Services;

// Generates guard-backup.cmd, a fully standalone Robocopy script that runs the
// same from the app, Task Scheduler, or a double-click.
public static class BackupScript
{
    public static void Write(Settings cfg)
    {
        string mirror = cfg.Mode == "Mirror" ? "/MIR" : "/E";
        // Mirror the SettingsStore load clamp: keep must never reach the script
        // as 0 or negative, or pruning could delete the folder just written.
        int keep = Math.Clamp(cfg.VersionsToKeep, 1, 365);
        string exDirs = ToOneLine(cfg.ExcludeDirs);
        string exFiles = ToOneLine(cfg.ExcludeFiles);
        var opts = new StringBuilder();
        // /XJ is MANDATORY: skips junction points. Without it the hidden
        // My Music / My Pictures / My Videos junctions in Documents cause
        // failed-directory errors on every run.
        opts.Append(mirror).Append(" /R:2 /W:5 /MT:16 /NP /NFL /NDL /XJ");
        if (exDirs.Length > 0) opts.Append(" /XD ").Append(exDirs);
        if (exFiles.Length > 0) opts.Append(" /XF ").Append(exFiles);

        var sb = new StringBuilder();
        sb.AppendLine("@echo off");
        sb.AppendLine("setlocal EnableExtensions");
        sb.AppendLine("REM ===========================================================================");
        sb.AppendLine("REM  guard-backup.cmd  -  GENERATED by GUARD.exe. Do not hand-edit;");
        sb.AppendLine("REM  your changes will be overwritten the next time you Save in the app.");
        sb.AppendLine("REM");
        sb.AppendLine("REM  USAGE:");
        sb.AppendLine("REM    guard-backup.cmd          run the backup for real (keeps window open)");
        sb.AppendLine("REM    guard-backup.cmd test     PREVIEW only - shows what WOULD change");
        sb.AppendLine("REM    guard-backup.cmd auto     silent (used by the scheduled task)");
        sb.AppendLine("REM ===========================================================================");
        sb.AppendLine();
        sb.AppendLine("set \"DEST=" + cfg.Dest + "\"");
        if (cfg.Versioned)
            sb.AppendLine("set \"KEEP=" + keep + "\"");
        sb.AppendLine("set \"LOGDIR=%~dp0Logs\"");
        sb.AppendLine("set \"LOG=%LOGDIR%\\backup_last.log\"");
        sb.AppendLine();
        sb.AppendLine("set \"DRY=\"");
        sb.AppendLine("set \"PAUSEATEND=1\"");
        sb.AppendLine("if /I \"%~1\"==\"test\" set \"DRY=/L\"");
        sb.AppendLine("if /I \"%~1\"==\"auto\" set \"PAUSEATEND=\"");
        sb.AppendLine();
        sb.AppendLine("set \"OPTS=" + opts + "\"");
        sb.AppendLine();
        sb.AppendLine("if not exist \"%LOGDIR%\" md \"%LOGDIR%\"");
        sb.AppendLine();
        if (cfg.Versioned)
        {
            // %date% is locale-formatted and wmic is removed from current
            // Windows 11, so PowerShell (present on every supported Windows)
            // is the only portable way to get a YYYY-MM-DD stamp in batch.
            sb.AppendLine("REM Versioned mode: each run copies into a dated subfolder of DEST and");
            sb.AppendLine("REM the oldest dated folders beyond KEEP are pruned after a clean run.");
            sb.AppendLine("set \"STAMP=\"");
            sb.AppendLine("for /f %%I in ('powershell -NoProfile -Command \"Get-Date -Format yyyy-MM-dd\"') do set \"STAMP=%%I\"");
            sb.AppendLine("if not defined STAMP (");
            sb.AppendLine("   echo ERROR: could not compute the date stamp for the versioned backup - aborting.");
            sb.AppendLine("   >\"%LOG%\" echo ERROR: could not compute the date stamp for the versioned backup - aborting.");
            sb.AppendLine("   goto :end");
            sb.AppendLine(")");
            sb.AppendLine("set \"RUNDEST=%DEST%\\%STAMP%\"");
            sb.AppendLine();
        }
        sb.AppendLine(">\"%LOG%\"  echo ===========================================================");
        sb.AppendLine(">>\"%LOG%\" echo  Backup     %date% %time%");
        sb.AppendLine(">>\"%LOG%\" echo  Destination: %DEST%");
        if (cfg.Versioned)
            sb.AppendLine(">>\"%LOG%\" echo  Version folder: %STAMP%  (keeping the newest %KEEP%)");
        sb.AppendLine("if defined DRY >>\"%LOG%\" echo  *** PREVIEW MODE - no changes made ***");
        sb.AppendLine(">>\"%LOG%\" echo ===========================================================");
        sb.AppendLine();
        sb.AppendLine("echo.");
        sb.AppendLine("echo Backup    destination: %DEST%");
        if (cfg.Versioned)
            sb.AppendLine("echo Version folder: %STAMP%  (keeping the newest %KEEP%)");
        sb.AppendLine("if defined DRY echo *** PREVIEW MODE - nothing will be copied or deleted ***");
        sb.AppendLine("echo Log file: %LOG%");
        sb.AppendLine("echo.");
        sb.AppendLine();
        sb.AppendLine("if not exist \"%DEST%\\\" (");
        sb.AppendLine("   echo ERROR: destination not reachable at %DEST%  - aborting.");
        sb.AppendLine("   >>\"%LOG%\" echo ERROR: destination not reachable at %DEST% - aborting.");
        sb.AppendLine("   goto :end");
        sb.AppendLine(")");
        sb.AppendLine();
        sb.AppendLine("set \"HADERR=\"");
        sb.AppendLine();
        // @@PROGRESS@@ markers feed the app's progress bar; emitted only under
        // GUARD_UI, sent to stdout only (never the log).
        var inc = new List<FolderPair>();
        foreach (var f in cfg.Folders) if (f.Include) inc.Add(f);
        string runDest = cfg.Versioned ? "%RUNDEST%" : "%DEST%";
        for (int i = 0; i < inc.Count; i++)
        {
            var f = inc[i];
            sb.AppendLine("if defined GUARD_UI echo @@PROGRESS@@ " + (i + 1) + " " + inc.Count + " " + MarkerSafe(f.SubFolder));
            sb.AppendLine("call :backup \"" + f.Source + "\" \"" + runDest + "\\" + f.SubFolder + "\"");
        }
        sb.AppendLine("if defined GUARD_UI echo @@PROGRESS@@ DONE");
        sb.AppendLine();
        sb.AppendLine(">>\"%LOG%\" echo.");
        sb.AppendLine("if defined HADERR (");
        sb.AppendLine("   >>\"%LOG%\" echo FINISHED WITH ERRORS   %date% %time%");
        sb.AppendLine("   echo.");
        sb.AppendLine("   echo Backup finished, but some folders reported errors - see the log.");
        sb.AppendLine(") else (");
        sb.AppendLine("   >>\"%LOG%\" echo FINISHED OK   %date% %time%");
        sb.AppendLine("   echo.");
        sb.AppendLine("   echo Backup finished successfully.");
        sb.AppendLine(")");
        if (cfg.Versioned)
        {
            sb.AppendLine("REM Prune only after a clean real run: if this run had errors the new");
            sb.AppendLine("REM version may be incomplete, so keeping extra old versions is safer.");
            sb.AppendLine("if not defined DRY if not defined HADERR call :prune");
        }
        sb.AppendLine("goto :end");
        sb.AppendLine();
        sb.AppendLine(":backup");
        sb.AppendLine("if not exist \"%~1\" (");
        sb.AppendLine("   echo SKIP  source not found: %~1");
        sb.AppendLine("   >>\"%LOG%\" echo.");
        sb.AppendLine("   >>\"%LOG%\" echo SKIP source not found: %~1");
        sb.AppendLine("   goto :eof");
        sb.AppendLine(")");
        sb.AppendLine("echo Backing up: %~1");
        sb.AppendLine(">>\"%LOG%\" echo.");
        sb.AppendLine(">>\"%LOG%\" echo --- %~1  =^> %~2");
        sb.AppendLine("robocopy \"%~1\" \"%~2\" %OPTS% %DRY% /LOG+:\"%LOG%\" /TEE");
        sb.AppendLine("if errorlevel 8 (");
        sb.AppendLine("   set \"HADERR=1\"");
        sb.AppendLine("   echo    !! errors copying %~1 - see the log");
        sb.AppendLine(")");
        sb.AppendLine("goto :eof");
        sb.AppendLine();
        if (cfg.Versioned)
        {
            // Deletion is deliberately narrow: only directories DIRECTLY under
            // DEST whose names are exactly YYYY-MM-DD (findstr whole-line digit
            // match) qualify, so any other content the user keeps at the
            // destination can never be touched. The dated names sort
            // lexicographically in date order, so dir /o:n lists oldest first
            // and the first EXCESS matches are the oldest versions.
            sb.AppendLine(":prune");
            sb.AppendLine("set \"EXCESS=\"");
            sb.AppendLine("set /a COUNT=0");
            sb.AppendLine("for /f \"delims=\" %%D in ('dir /b /ad /o:n \"%DEST%\" 2^>nul ^| findstr /r \"^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]$\"') do set /a COUNT+=1");
            sb.AppendLine("set /a EXCESS=COUNT-KEEP");
            sb.AppendLine("if %EXCESS% leq 0 goto :eof");
            sb.AppendLine(">>\"%LOG%\" echo.");
            sb.AppendLine(">>\"%LOG%\" echo Pruning %EXCESS% old version folder(s), keeping the newest %KEEP%.");
            sb.AppendLine("for /f \"delims=\" %%D in ('dir /b /ad /o:n \"%DEST%\" 2^>nul ^| findstr /r \"^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]$\"') do call :prunedel \"%%D\"");
            sb.AppendLine("goto :eof");
            sb.AppendLine();
            sb.AppendLine(":prunedel");
            sb.AppendLine("if %EXCESS% leq 0 goto :eof");
            sb.AppendLine("REM Never delete the folder this run just wrote, whatever the count says.");
            sb.AppendLine("if /I \"%~1\"==\"%STAMP%\" goto :eof");
            sb.AppendLine("echo Removing old version: %~1");
            sb.AppendLine(">>\"%LOG%\" echo Removed old version: %~1");
            sb.AppendLine("rd /s /q \"%DEST%\\%~1\"");
            sb.AppendLine("set /a EXCESS-=1");
            sb.AppendLine("goto :eof");
            sb.AppendLine();
        }
        sb.AppendLine(":end");
        sb.AppendLine("endlocal");
        sb.AppendLine("echo.");
        sb.AppendLine("if defined PAUSEATEND pause");
        File.WriteAllText(GuardPaths.ScriptPath, sb.ToString());
    }

    // Strip characters that would break a batch `echo` so a subfolder name is
    // safe to embed in an @@PROGRESS@@ marker line.
    private static string MarkerSafe(string s)
    {
        if (string.IsNullOrEmpty(s)) return "";
        var sb = new StringBuilder();
        foreach (char c in s)
            sb.Append("&<>|^%\"".IndexOf(c) >= 0 ? ' ' : c);
        return sb.ToString().Trim();
    }

    private static string ToOneLine(string multiline)
    {
        if (string.IsNullOrEmpty(multiline)) return "";
        // Handle every newline form, including the bare CR a WinUI multi-line
        // TextBox uses, so each excluded name becomes its own /XD or /XF token.
        var parts = multiline.Replace("\r\n", "\n").Replace("\r", "\n").Split('\n');
        var keep = new List<string>();
        foreach (var p in parts) { var t = p.Trim(); if (t.Length > 0) keep.Add(t); }
        return string.Join(" ", keep.ToArray());
    }
}
