using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using GuardWui3.Models;

namespace GuardWui3.Services;

// Generates guard-backup.cmd, a fully standalone Robocopy script that runs the
// same from the app, Task Scheduler, or a double-click.
//
// Exit codes (the headless helper maps these to toasts; see
// HeadlessBackupRunner): 0 = finished cleanly, 1 = finished with errors,
// 2 = could not run (destination unreachable / setup failure), 3 = nothing to
// do (on-connect gate, or another backup already holds the run lock).
public static class BackupScript
{
    public static void Write(Settings cfg)
        => AtomicFile.WriteAllText(GuardPaths.ScriptPath, Generate(cfg));

    // Split from Write so the generated text is testable without touching disk.
    public static string Generate(Settings cfg)
    {
        string mirror = cfg.Mode == "Mirror" ? "/MIR" : "/E";
        // Mirror the SettingsStore load clamp: keep must never reach the script
        // as 0 or negative, or pruning could delete the folder just written.
        int keep = Math.Clamp(cfg.VersionsToKeep, 1, 365);
        string exDirs = JoinTokens(cfg.EffectiveExcludeDirs());
        string exFiles = JoinTokens(cfg.EffectiveExcludeFiles());
        // /XJ is MANDATORY: skips junction points. Without it the hidden
        // My Music / My Pictures / My Videos junctions in Documents cause
        // failed-directory errors on every run.
        string optsCommon = mirror + " /R:2 /W:5 /MT:16 /NP /NDL /XJ";
        string optsTail = "";
        if (exDirs.Length > 0) optsTail += " /XD " + exDirs;
        if (exFiles.Length > 0) optsTail += " /XF " + exFiles;
        // The two listing modes differ only by the file-list flag (set via
        // GUARD_UI). Unattended runs use /NFL for a compact log. UI runs drop
        // /NFL and add /BYTES so robocopy prints one line per copied file with a
        // raw byte count, which the app sums for within-folder progress; cost is
        // a longer log on interactive runs only.
        string optsCompact = optsCommon + " /NFL" + optsTail;
        string optsUi = optsCommon + " /BYTES" + optsTail;
        string dest = DestValue(cfg.Dest);
        // Drive-letter drift: only a letter-rooted destination with a recorded
        // volume serial gets the re-find prologue (UNC paths have no letter to
        // drift, and without a serial there is nothing to search by).
        bool drift = cfg.DestVolumeSerial.Length > 0 && dest.Length >= 2 && dest[1] == ':';

        var sb = new StringBuilder();
        sb.AppendLine("@echo off");
        sb.AppendLine("setlocal EnableExtensions");
        // This file is written as UTF-8, but cmd parses batch lines in the
        // console codepage (OEM by default), so any non-ASCII character in the
        // embedded destination/source paths or exclude patterns was mangled
        // and every path test failed. Switching the console to UTF-8 makes the
        // rest of the file decode as written (cmd re-decodes each line as it
        // reads it); echo and robocopy output then also arrive as UTF-8, which
        // is what the app already reads (BackupHealth's log tail, the UI's
        // capture). The default sources dodge this via %USERPROFILE% (expanded
        // at run time), which is why browsed-in paths were the ones that broke.
        sb.AppendLine("chcp 65001 >nul");
        sb.AppendLine("REM ===========================================================================");
        sb.AppendLine("REM  guard-backup.cmd  -  GENERATED by GUARD.exe. Do not hand-edit;");
        sb.AppendLine("REM  your changes will be overwritten the next time you Save in the app.");
        sb.AppendLine("REM");
        sb.AppendLine("REM  USAGE:");
        sb.AppendLine("REM    guard-backup.cmd          run the backup for real (keeps window open)");
        sb.AppendLine("REM    guard-backup.cmd test     PREVIEW only - shows what WOULD change");
        sb.AppendLine("REM    guard-backup.cmd auto     silent (used by the scheduled task)");
        sb.AppendLine("REM    guard-backup.cmd onconnect");
        sb.AppendLine("REM                              silent; backs up only if the destination is");
        sb.AppendLine("REM                              reachable and no backup succeeded yet today");
        sb.AppendLine("REM                              (used by the on-connect scheduled task)");
        sb.AppendLine("REM");
        sb.AppendLine("REM  EXIT CODES: 0 ok, 1 finished with errors, 2 could not run,");
        sb.AppendLine("REM              3 nothing to do (on-connect skip, or already running).");
        sb.AppendLine("REM ===========================================================================");
        sb.AppendLine();
        sb.AppendLine("set \"DEST=" + dest + "\"");
        if (drift)
        {
            // Split so a re-found drive letter can be spliced onto the same
            // tail; DESTROOT keeps the old letter for the log note.
            sb.AppendLine("set \"DESTROOT=" + dest.Substring(0, 2) + "\"");
            sb.AppendLine("set \"DESTTAIL=" + dest.Substring(2) + "\"");
        }
        if (cfg.Versioned)
            sb.AppendLine("set \"KEEP=" + keep + "\"");
        sb.AppendLine("set \"LOGDIR=%~dp0Logs\"");
        sb.AppendLine("set \"LOG=%LOGDIR%\\backup_last.log\"");
        sb.AppendLine("set \"LOCKFILE=%LOGDIR%\\backup-running.lock\"");
        sb.AppendLine();
        sb.AppendLine("set \"DRY=\"");
        sb.AppendLine("set \"PAUSEATEND=1\"");
        sb.AppendLine("if /I \"%~1\"==\"test\" set \"DRY=/L\"");
        // Preview must never touch backup_last.log: BackupHealth reads that file's
        // FINISHED line and mtime to show "last backup succeeded", and Open Last
        // Log opens it too. A preview that shared it would overwrite real backup
        // history with a no-op run's result the moment someone clicks Preview.
        sb.AppendLine("if defined DRY set \"LOG=%LOGDIR%\\backup_preview.log\"");
        sb.AppendLine("if /I \"%~1\"==\"auto\" set \"PAUSEATEND=\"");
        sb.AppendLine("if /I \"%~1\"==\"onconnect\" set \"PAUSEATEND=\"");
        sb.AppendLine("if /I \"%~1\"==\"onconnect\" set \"ONCONNECT=1\"");
        sb.AppendLine();
        if (drift)
        {
            // USB drives change letters between plugs. When the saved letter is
            // gone, one PowerShell CIM lookup re-finds the volume by the serial
            // recorded at save time; the happy path (letter still valid) stays
            // PowerShell-free, so the every-15-minutes on-connect check remains
            // cheap whenever the drive is actually there. Runs BEFORE the
            // on-connect gate so that gate probes the drive's real location.
            sb.AppendLine("REM The saved drive letter can change between plugs; if it is gone, find");
            sb.AppendLine("REM the same volume by its serial number and follow it.");
            sb.AppendLine("if exist \"%DEST%\\\" goto :driftdone");
            sb.AppendLine("set \"NEWDRIVE=\"");
            sb.AppendLine("for /f \"delims=\" %%L in ('powershell -NoProfile -EncodedCommand "
                + DriftLookupEncoded(cfg.DestVolumeSerial) + "') do set \"NEWDRIVE=%%L\"");
            sb.AppendLine("if defined NEWDRIVE if /I not \"%NEWDRIVE%\"==\"%DESTROOT%\" (");
            sb.AppendLine("   set \"DEST=%NEWDRIVE%%DESTTAIL%\"");
            sb.AppendLine("   set \"DRIFTED=1\"");
            sb.AppendLine("   echo NOTE: backup drive found at %NEWDRIVE% instead of %DESTROOT%; using it.");
            sb.AppendLine(")");
            sb.AppendLine(":driftdone");
            sb.AppendLine();
        }
        // On-connect gate: the periodic task fires this every few minutes, so it
        // must cost nothing when there's nothing to do. Exit silently (before the
        // log header, so the last real backup log is never overwritten) when the
        // destination is absent or the stamp already records a successful run
        // today. The stamp holds %DATE% verbatim; findstr /x compares it as
        // written, so locale date formats are irrelevant. A failed run doesn't
        // update the stamp (see the HADERR branch), so the next check retries
        // instead of skipping the day. Exit code 3 = "nothing to do", so the
        // hidden helper never mistakes a quiet skip for a failure.
        sb.AppendLine("set \"OCSTAMP=%~dp0onconnect-stamp.txt\"");
        sb.AppendLine("if not defined ONCONNECT goto :checked");
        sb.AppendLine("if not exist \"%DEST%\\\" exit /b 3");
        sb.AppendLine("findstr /l /x /c:\"%DATE%\" \"%OCSTAMP%\" >nul 2>&1");
        sb.AppendLine("if not errorlevel 1 exit /b 3");
        sb.AppendLine(":checked");
        sb.AppendLine();
        sb.AppendLine("set \"OPTS=" + optsCompact + "\"");
        // UI runs (launched by GUARD.exe, which sets GUARD_UI) stream per-file
        // byte lines so the app can show within-folder progress.
        sb.AppendLine("if defined GUARD_UI set \"OPTS=" + optsUi + "\"");
        sb.AppendLine();
        sb.AppendLine("if not exist \"%LOGDIR%\" md \"%LOGDIR%\"");
        sb.AppendLine();
        // Single-run lock: fd 9 holds LOCKFILE open for the whole of :main, so
        // a scheduled fire during an in-app run (or vice versa) cannot corrupt
        // the shared log or race robocopy - the loser's redirect fails, :main
        // never runs, RC stays undefined, and it bows out as "nothing to do".
        // The 2>nul only hides cmd's sharing-violation complaint from that
        // losing attempt. A killed run releases the handle with the process,
        // and the leftover lock FILE is harmless (only openability matters).
        sb.AppendLine("set \"RC=\"");
        sb.AppendLine("2>nul ( 9>\"%LOCKFILE%\" call :main )");
        sb.AppendLine("if not defined RC (");
        sb.AppendLine("   echo Another backup is already running - this run was skipped.");
        sb.AppendLine("   set \"RC=3\"");
        sb.AppendLine(")");
        sb.AppendLine("echo.");
        // The pause must run BEFORE endlocal: PAUSEATEND is set inside the
        // setlocal scope, so endlocal discards it and a pause placed after
        // never fires - a double-clicked run's window then closes instantly.
        // %RC% on the same line expands before endlocal clears it.
        sb.AppendLine("if defined PAUSEATEND pause");
        sb.AppendLine("endlocal & exit /b %RC%");
        sb.AppendLine();
        sb.AppendLine(":main");
        if (cfg.Versioned)
        {
            // %date% is locale-formatted and wmic is removed from current
            // Windows 11, so PowerShell (present on every supported Windows)
            // is the only portable way to get a YYYY-MM-DD stamp in batch.
            sb.AppendLine("REM Versioned mode: each run copies into a dated subfolder of DEST and");
            sb.AppendLine("REM the oldest dated folders beyond KEEP are pruned after a clean run.");
            sb.AppendLine("set \"STAMP=\"");
            sb.AppendLine("for /f %%I in ('powershell -NoProfile -Command \"Get-Date -Format yyyy-MM-dd\"') do set \"STAMP=%%I\"");
            sb.AppendLine("if not defined STAMP (");
            sb.AppendLine("   echo ERROR: could not compute the date stamp for the versioned backup - aborting.");
            sb.AppendLine("   >\"%LOG%\" echo ERROR: could not compute the date stamp for the versioned backup - aborting.");
            sb.AppendLine("   set \"RC=2\"");
            sb.AppendLine("   goto :eof");
            sb.AppendLine(")");
            sb.AppendLine("set \"RUNDEST=%DEST%\\%STAMP%\"");
            sb.AppendLine();
        }
        sb.AppendLine(">\"%LOG%\"  echo ===========================================================");
        sb.AppendLine(">>\"%LOG%\" echo  Backup     %date% %time%");
        // %DEST% is quoted wherever echo re-expands it: unquoted, a & < > | or ^
        // in the path would be parsed as a cmd operator mid-message.
        sb.AppendLine(">>\"%LOG%\" echo  Destination: \"%DEST%\"");
        if (drift)
            sb.AppendLine("if defined DRIFTED >>\"%LOG%\" echo  NOTE: destination drive found at %NEWDRIVE% ^(was %DESTROOT%^); it changed drive letters.");
        if (cfg.Versioned)
            sb.AppendLine(">>\"%LOG%\" echo  Version folder: %STAMP%  (keeping the newest %KEEP%)");
        sb.AppendLine("if defined DRY >>\"%LOG%\" echo  *** PREVIEW MODE - no changes made ***");
        sb.AppendLine(">>\"%LOG%\" echo ===========================================================");
        sb.AppendLine();
        sb.AppendLine("echo.");
        sb.AppendLine("echo Backup    destination: \"%DEST%\"");
        if (cfg.Versioned)
            sb.AppendLine("echo Version folder: %STAMP%  (keeping the newest %KEEP%)");
        sb.AppendLine("if defined DRY echo *** PREVIEW MODE - nothing will be copied or deleted ***");
        sb.AppendLine("echo Log file: %LOG%");
        sb.AppendLine("echo.");
        sb.AppendLine();
        sb.AppendLine("if not exist \"%DEST%\\\" (");
        sb.AppendLine("   echo ERROR: destination not reachable at \"%DEST%\"  - aborting.");
        sb.AppendLine("   >>\"%LOG%\" echo ERROR: destination not reachable at \"%DEST%\" - aborting.");
        sb.AppendLine("   set \"RC=2\"");
        sb.AppendLine("   goto :eof");
        sb.AppendLine(")");
        sb.AppendLine();
        sb.AppendLine("set \"HADERR=\"");
        sb.AppendLine();
        // @@PROGRESS@@ markers feed the app's progress bar; emitted only under
        // GUARD_UI, sent to stdout only (never the log).
        var inc = new List<FolderPair>();
        foreach (var f in cfg.Folders) if (f.Include) inc.Add(f);
        string runDest = cfg.Versioned ? "%RUNDEST%" : "%DEST%";
        for (int i = 0; i < inc.Count; i++)
        {
            var f = inc[i];
            // A stray leading/trailing backslash on the subfolder (or an empty
            // legacy one) must not leave the quoted destination ending in \",
            // which robocopy's parser reads as an escaped quote; "." keeps an
            // empty subfolder meaning "the destination root itself".
            string sub = f.SubFolder.Trim().Trim('\\');
            sb.AppendLine("if defined GUARD_UI echo @@PROGRESS@@ " + (i + 1) + " " + inc.Count + " " + MarkerSafe(f.SubFolder));
            sb.AppendLine("call :backup \"" + SourceArg(f.Source) + "\" \"" + runDest + "\\" + (sub.Length > 0 ? sub : ".") + "\"");
        }
        sb.AppendLine("if defined GUARD_UI echo @@PROGRESS@@ DONE");
        sb.AppendLine();
        sb.AppendLine(">>\"%LOG%\" echo.");
        sb.AppendLine("if defined HADERR (");
        sb.AppendLine("   >>\"%LOG%\" echo FINISHED WITH ERRORS   %date% %time%");
        sb.AppendLine("   echo.");
        sb.AppendLine("   echo Backup finished, but some folders reported errors - see the log.");
        sb.AppendLine("   set \"RC=1\"");
        sb.AppendLine(") else (");
        sb.AppendLine("   >>\"%LOG%\" echo FINISHED OK   %date% %time%");
        sb.AppendLine("   echo.");
        sb.AppendLine("   echo Backup finished successfully.");
        // Stamp only clean on-connect runs (an error should retry next check; the
        // DRY guard is belt-and-braces, the task never passes "test"). %DATE%
        // expands at the finish, so a run crossing midnight stamps the new day as
        // covered.
        sb.AppendLine("   if defined ONCONNECT if not defined DRY >\"%OCSTAMP%\" echo %DATE%");
        sb.AppendLine("   set \"RC=0\"");
        sb.AppendLine(")");
        if (cfg.Versioned)
        {
            sb.AppendLine("REM Prune only after a clean real run: if this run had errors the new");
            sb.AppendLine("REM version may be incomplete, so keeping extra old versions is safer.");
            sb.AppendLine("if not defined DRY if not defined HADERR call :prune");
        }
        sb.AppendLine("goto :eof");
        sb.AppendLine();
        sb.AppendLine(":backup");
        sb.AppendLine("if not exist \"%~1\" (");
        sb.AppendLine("   echo SKIP  source not found: \"%~1\"");
        sb.AppendLine("   >>\"%LOG%\" echo.");
        sb.AppendLine("   >>\"%LOG%\" echo SKIP source not found: \"%~1\"");
        sb.AppendLine("   goto :eof");
        sb.AppendLine(")");
        sb.AppendLine("echo Backing up: \"%~1\"");
        sb.AppendLine(">>\"%LOG%\" echo.");
        sb.AppendLine(">>\"%LOG%\" echo --- \"%~1\"  =^> \"%~2\"");
        sb.AppendLine("robocopy \"%~1\" \"%~2\" %OPTS% %DRY% /LOG+:\"%LOG%\" /TEE");
        sb.AppendLine("if errorlevel 8 (");
        sb.AppendLine("   set \"HADERR=1\"");
        sb.AppendLine("   echo    !! errors copying \"%~1\" - see the log");
        sb.AppendLine(")");
        sb.AppendLine("goto :eof");
        sb.AppendLine();
        if (cfg.Versioned)
        {
            // Deletion is deliberately narrow: only directories DIRECTLY under
            // DEST whose names are exactly YYYY-MM-DD (findstr whole-line digit
            // match) qualify, so any other content the user keeps at the
            // destination can never be touched. The dated names sort
            // lexicographically in date order, so dir /o:n lists oldest first
            // and the first EXCESS matches are the oldest versions.
            sb.AppendLine(":prune");
            sb.AppendLine("set \"EXCESS=\"");
            sb.AppendLine("set /a COUNT=0");
            sb.AppendLine("for /f \"delims=\" %%D in ('dir /b /ad /o:n \"%DEST%\" 2^>nul ^| findstr /r \"^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]$\"') do set /a COUNT+=1");
            sb.AppendLine("set /a EXCESS=COUNT-KEEP");
            sb.AppendLine("if %EXCESS% leq 0 goto :eof");
            sb.AppendLine(">>\"%LOG%\" echo.");
            sb.AppendLine(">>\"%LOG%\" echo Pruning %EXCESS% old version folder(s), keeping the newest %KEEP%.");
            sb.AppendLine("for /f \"delims=\" %%D in ('dir /b /ad /o:n \"%DEST%\" 2^>nul ^| findstr /r \"^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]$\"') do call :prunedel \"%%D\"");
            sb.AppendLine("goto :eof");
            sb.AppendLine();
            sb.AppendLine(":prunedel");
            sb.AppendLine("if %EXCESS% leq 0 goto :eof");
            sb.AppendLine("REM Never delete the folder this run just wrote, whatever the count says.");
            sb.AppendLine("if /I \"%~1\"==\"%STAMP%\" goto :eof");
            sb.AppendLine("echo Removing old version: %~1");
            sb.AppendLine(">>\"%LOG%\" echo Removed old version: %~1");
            sb.AppendLine("rd /s /q \"%DEST%\\%~1\"");
            sb.AppendLine("set /a EXCESS-=1");
            sb.AppendLine("goto :eof");
            sb.AppendLine();
        }
        return sb.ToString();
    }

    // The one-line PowerShell that maps the recorded volume serial back to its
    // current drive letter ("F:"), base64-encoded (UTF-16, -EncodedCommand) at
    // generation time so no quoting survives into the batch line. CIM's
    // Win32_LogicalDisk.VolumeSerialNumber is the same 8-hex-digit value
    // VolumeInfo records.
    private static string DriftLookupEncoded(string serialHex)
    {
        // Serial is hex digits only by construction; strip anything else so a
        // hand-edited ini value cannot smuggle script into the command.
        var sb = new StringBuilder();
        foreach (char c in serialHex.Trim().ToUpperInvariant())
            if (c is (>= '0' and <= '9') or (>= 'A' and <= 'F')) sb.Append(c);
        string ps = "$d = (Get-CimInstance Win32_LogicalDisk -Filter \"VolumeSerialNumber='" + sb +
                    "'\" | Select-Object -First 1).DeviceID; if ($d) { Write-Output $d }";
        return Convert.ToBase64String(Encoding.Unicode.GetBytes(ps));
    }

    // A quoted path argument must never end in a backslash: robocopy parses \"
    // as an escaped quote and mangles every argument after it. A bare or
    // slashed drive root becomes "X:\." ("X:" alone is drive-relative and
    // would resolve against that drive's current directory).
    private static string SourceArg(string source)
    {
        string s = (source ?? "").Trim();
        if (s.Length == 2 && s[1] == ':') return s + "\\.";
        if (!s.EndsWith("\\")) return s;
        string t = s.TrimEnd('\\');
        return t.Length == 2 && t[1] == ':' ? t + "\\." : t;
    }

    // DEST composes as %DEST%\<sub>, so it must not end in a backslash - except
    // a drive root, which keeps "X:\" ("X:" alone is drive-relative; the
    // "E:\\Sub" the composition then yields is harmless to robocopy and cmd).
    private static string DestValue(string dest)
    {
        string d = (dest ?? "").Trim();
        if (d.Length == 2 && d[1] == ':') return d + "\\";
        string t = d.TrimEnd('\\');
        return t.Length == 2 && t[1] == ':' ? t + "\\" : t;
    }

    // Strip characters that would break a batch `echo` so a subfolder name is
    // safe to embed in an @@PROGRESS@@ marker line.
    private static string MarkerSafe(string s)
    {
        if (string.IsNullOrEmpty(s)) return "";
        var sb = new StringBuilder();
        foreach (char c in s)
            sb.Append("&<>|^%\"".IndexOf(c) >= 0 ? ' ' : c);
        return sb.ToString().Trim();
    }

    // Quote any token holding a space ("System Volume Information") so robocopy
    // reads it as a single /XD or /XF argument; the quotes survive the
    // set "OPTS=..." wrapper, which only strips its own outer pair.
    private static string JoinTokens(List<string> tokens)
    {
        var sb = new StringBuilder();
        foreach (var t in tokens)
        {
            if (sb.Length > 0) sb.Append(' ');
            sb.Append(t.Contains(' ') ? "\"" + t + "\"" : t);
        }
        return sb.ToString();
    }
}
