using System;
using System.IO;
using System.Net;
using System.Text;
using GuardWui3.Models;

namespace GuardWui3.Services;

// Generates guard-system-image.cmd, a standalone script that drives the built-in
// wbadmin tool to capture a full bare-metal system image. This is the engine
// isolation layer (the BackupScript analogue): swapping wbadmin for another
// imager later touches only this file. Like the backup script it runs the same
// whether launched elevated by the app or by the SYSTEM scheduled task.
//
// wbadmin needs Administrator, so the app never runs this directly: it goes
// through ProcessRunner.RunPowerShellElevated (one UAC prompt) or the SYSTEM
// scheduled task. Output cannot cross the elevation boundary, so every line of
// progress and the final result are written to the log, which the UI tails.
public static class SystemImageScript
{
    public static void Write(Settings cfg)
    {
        string target = TargetArg(cfg);

        var sb = new StringBuilder();
        sb.AppendLine("@echo off");
        sb.AppendLine("setlocal EnableExtensions");
        sb.AppendLine("REM ===========================================================================");
        sb.AppendLine("REM  guard-system-image.cmd  -  GENERATED by GUARD.exe. Do not hand-edit;");
        sb.AppendLine("REM  your changes will be overwritten the next time you Save in the app.");
        sb.AppendLine("REM");
        sb.AppendLine("REM  Creates a full bare-metal system image with the built-in wbadmin tool.");
        sb.AppendLine("REM  Requires Administrator: GUARD runs it elevated, the scheduled task as SYSTEM.");
        sb.AppendLine("REM");
        sb.AppendLine("REM  USAGE:");
        sb.AppendLine("REM    guard-system-image.cmd        create the image now");
        sb.AppendLine("REM    guard-system-image.cmd auto   same; the arg is kept for the scheduled task");
        sb.AppendLine("REM ===========================================================================");
        sb.AppendLine();
        sb.AppendLine("set \"TARGET=" + target + "\"");
        sb.AppendLine("set \"LOGDIR=%~dp0Logs\"");
        sb.AppendLine("set \"LOG=%LOGDIR%\\system-image_last.log\"");
        sb.AppendLine("if not exist \"%LOGDIR%\" md \"%LOGDIR%\"");
        sb.AppendLine();
        sb.AppendLine(">\"%LOG%\"  echo ===========================================================");
        sb.AppendLine(">>\"%LOG%\" echo  System image   %date% %time%");
        // Quoted so a & or ^ in a share path is not parsed as a cmd operator.
        sb.AppendLine(">>\"%LOG%\" echo  Target: \"%TARGET%\"");
        sb.AppendLine(">>\"%LOG%\" echo ===========================================================");
        sb.AppendLine(">>\"%LOG%\" echo.");
        sb.AppendLine();
        // -allCritical grabs every volume needed to boot (EFI / system / recovery
        // / Windows); -quiet suppresses the interactive confirmation. All wbadmin
        // output (the per-volume "copied (NN%)" lines the UI parses, plus errors)
        // is redirected to the log because nothing reaches the hidden console.
        sb.AppendLine("wbadmin start backup -backupTarget:\"%TARGET%\" -allCritical -quiet >>\"%LOG%\" 2>&1");
        sb.AppendLine("set \"RC=%ERRORLEVEL%\"");
        sb.AppendLine();
        sb.AppendLine(">>\"%LOG%\" echo.");
        sb.AppendLine("if \"%RC%\"==\"0\" (");
        sb.AppendLine("   >>\"%LOG%\" echo FINISHED OK   %date% %time%");
        sb.AppendLine(") else (");
        sb.AppendLine("   >>\"%LOG%\" echo FINISHED WITH ERRORS ^(exit %RC%^)   %date% %time%");
        sb.AppendLine(")");
        // Propagate wbadmin's exit code: the elevated launcher reads it as the
        // authoritative success/failure signal (the log tail is just for display).
        sb.AppendLine("endlocal & exit /b %RC%");
        File.WriteAllText(GuardPaths.SystemImageScriptPath, sb.ToString());
    }

    // wbadmin -backupTarget wants "E:" for a local disk (drive letter + colon, no
    // trailing slash) and the raw UNC for a share.
    private static string TargetArg(Settings cfg)
    {
        string t = (cfg.ImageTarget ?? "").Trim();
        if (cfg.ImageTargetKind == "NetworkShare")
            return t.TrimEnd('\\');
        // Local disk: reduce "X:\" or "X:\folder" to just "X:".
        if (t.Length >= 2 && t[1] == ':')
            return t.Substring(0, 2);
        return t.TrimEnd('\\');
    }

    // Refuse a local-disk target on the same volume Windows lives on: -allCritical
    // captures the system drive, so it can never also be the destination. UNC
    // targets are never the source, so they always pass.
    public static bool IsSystemDrive(string target)
    {
        string? d = DriveLetter(target);
        if (d == null) return false;
        string? sd = DriveLetter(Environment.GetFolderPath(Environment.SpecialFolder.Windows));
        return d.Equals(sd, StringComparison.OrdinalIgnoreCase);
    }

    private static string? DriveLetter(string? p)
    {
        if (string.IsNullOrWhiteSpace(p) || p.Length < 2 || p[1] != ':') return null;
        return p.Substring(0, 1).ToUpperInvariant();
    }

    // Resolve the server name in a UNC image target to its IPv4 address, returning
    // the path to type in the Windows recovery environment. WinRE has no mDNS / NetBIOS
    // resolver, so a share addressed by a ".local" or NetBIOS name (e.g. a Synology's
    // "\\nas\home\...") does not resolve there - only a literal IP does. Returns null
    // when the path is not a UNC, the host is already an IP, or it cannot be resolved
    // (the caller then falls back to showing the original path). Blocking DNS; call
    // off the UI thread.
    public static string? ResolveUncToIp(string? uncPath)
    {
        string p = (uncPath ?? "").Trim();
        if (!p.StartsWith(@"\\")) return null;
        string body = p.Substring(2);
        int slash = body.IndexOf('\\');
        if (slash <= 0) return null;
        string host = body.Substring(0, slash);
        string rest = body.Substring(slash);          // keeps the leading backslash
        if (IPAddress.TryParse(host, out _)) return null;   // already an IP
        try
        {
            var ip = Array.Find(Dns.GetHostAddresses(host),
                a => a.AddressFamily == System.Net.Sockets.AddressFamily.InterNetwork);
            return ip == null ? null : @"\\" + ip + rest;
        }
        catch { return null; }
    }

    // wbadmin ships on Pro/Enterprise/Education/LTSC but not on Home; `where` finds
    // it on PATH. Used to self-disable on-demand and scheduled imaging gracefully.
    public static bool IsWbadminAvailable()
    {
        try
        {
            string o = ProcessRunner.RunCapture("where", "wbadmin");
            return o.IndexOf("wbadmin", StringComparison.OrdinalIgnoreCase) >= 0;
        }
        catch { return false; }
    }
}
